---
title: "Assignment: Intro to R"
author: Sarah Meister
    - 
date: 2015-11-02
layout: page
sidebar: false
tag:
    - Lessons
    - Assignment
    - IntroR
categories:
    - Lessons
    - IntroR
    
output: html_vignette
---

# Intro to R Assignment #

1. Create the following vectors in R:
	
* a = 1 to 10
* b = 11 to 20

Use vector arithmetic to multiply these vectors and call the result c.  Select subsets of c to identify the following.

A. What is the 5th element of c?
B. What are all of the elements of c which are greater than 50?

2. Use R to create the following two matrices and multiply them. Make a new object of the resulting matrix (choose your own object names!)

alpha: 

```{r, echo=FALSE}


|7 | 9 | 12|
|2 | 4 | 13|
```

beta: 

| &nbsp;|&nbsp; |&nbsp; | &nbsp;|
|--- | --- | --- | --- |
|1 | 7 | 12 | 19|
|2 | 8 | 13 | 20|
|3 | 9 | 14 | 21|

3. Load the `datasets` package and make a new dataframe with the `mtcars` dataset. 

What are the means of the columns? Hint: use a loop function. 

Make new vectors with:

A. the column mpg
B. the fourth column
C. the third and fifth row

Use the `subset()` function to make a new vector where the hp is greater than 100

4. Make a vector with the following arguments: "cat", "dog", "cow", "pig". Make a combination for loop and  {if/else expression that prints the second argument. 
5. Create a function called `stats` that takes two arguments and prints the mean and standard deviation of the first argument and the median of the second argument. 

Hint: use the built-in `mean()`, `median()`, `sd()` and `print()` functions

Use your function with the `disp` and `drat` columns from the `mtcars` dataset. 
