---
title: "Introduction to R"
author: "Sarah Meister"
date: '2015-11-02'
output: html_document
fontsize: 8pt
header-includes: \input{../slideOptions.tex}
layout: page
classoption: xcolor=dvipsnames
sidebar: no
slide-level: 1
tag:
- Lessons
- Slides
- IntroR
categories:
- Lessons
- IntroR
---
# Now let's code! #

Download the airQuality.csv file from our [Github repo](https://github.com/codeasmanuscript/workshops/tree/master/lessons/rintro) and import it into R using the `read.csv` function


```{r, collapse=TRUE}
airQuality <- read.csv("airQuality.csv", header = TRUE)
```

Now let's look at the data using a few different functions

```{r, collapse=TRUE}
head(airQuality)

head(airQuality, n=8)

tail(airQuality)

str(airQuality)

nrow(airQuality)

ncol(airQuality)
```

Okay time to subset our data

```{r, collapse=TRUE}

rowThree <- airQuality[3, ]

colFour <- airQuality[ ,4]

ozone <- airQuality$Ozone

highTemp <- airQuality[airQuality$Temp > 70, ]

may <- airQuality[airQuality$Month == "May", ]

highTempOrMay <- airQuality[which(airQuality$Month == "May" | airQuality$Temp > 70), ]
```