---
title: "Introduction to R"
published: false
author: Sarah Meister
date: 2015-11-02
layout: page
sidebar: false
tag:
    - Lessons
    - Slides
    - IntroR
    - R
categories:
    - Lessons
    - IntroR
    - R
---
    
# Welcome to our R introduction workshop #

## Purpose: ##

To introduce you to the R language and common data manipulations used in R

# What is R and why do I need to learn it? #

R is an object-oritented programming language for statistical computing and graphics.

Benefits of R:

1. Easily extendible through **FREE** R packages
2. Active community (lots on online help)
3. Able to produce publication-quality graphs, and dynamic and interactive graphs with additional packages (did I mention they were **FREE**??)
4. For computationally intensive tasks, R objects can be manipulated with C, C++, Java, .NET or Python code 
5. Has it's own flavor of Markdown, making R code easily documented and shareable (which you will be learning in another lesson)

## Learning objectives ##

After this workshop, our expectation is that you will be able to:

1. Understand the "grammar" of the R language
2. Import and export data into R
3. View data in R and perform basic calculations & manipulations
4. Make and use a basic R function 
5. Understand and use the useful built-in loop functions

